tip_bundle_test_homepage:
    path:     /tip
    defaults: { _controller: TamagoTipsManagerBundle:TipsManager:index }

tip_feedback:
    path:     /tip/{id}/feedback/{feedback}
    defaults: { _controller: TamagoTipsManagerBundle:TipsManager:feedback }