language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - evan.owens@tamago-db.com
