language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - evan.owens@tamago-db.com
